import { useState } from 'react'
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card'
import { Button } from '@/components/ui/button'
import { FileText, Volume2, VolumeX, Download } from 'lucide-react'
import { LoadingSpinner } from '@/components/ui/loading-spinner'

interface AnalysisResultsProps {
  englishAnalysis?: string
  audioUrl?: string
  loading?: boolean
}

export function AnalysisResults({ englishAnalysis, audioUrl, loading }: AnalysisResultsProps) {
  const [isPlaying, setIsPlaying] = useState(false)

  const handlePlayAudio = () => {
    if (audioUrl) {
      const audio = new Audio(audioUrl)
      audio.play()
      setIsPlaying(true)
      audio.onended = () => setIsPlaying(false)
    }
  }

  const handleDownloadAudio = () => {
    if (audioUrl) {
      const link = document.createElement('a')
      link.href = audioUrl
      link.download = 'medical-analysis-audio.mp3'
      document.body.appendChild(link)
      link.click()
      document.body.removeChild(link)
    }
  }

  if (loading) {
    return (
      <Card>
        <CardContent className="flex items-center justify-center py-12">
          <div className="text-center space-y-4">
            <LoadingSpinner size="lg" />
            <p className="text-gray-600">Analyzing your medical report...</p>
            <p className="text-sm text-gray-500">This may take a few moments</p>
          </div>
        </CardContent>
      </Card>
    )
  }

  return (
    <div className="space-y-6">
      {/* English Analysis */}
      {englishAnalysis && (
        <Card>
          <CardHeader>
            <CardTitle className="flex items-center space-x-2">
              <FileText className="w-5 h-5 text-blue-600" />
              <span>Medical Analysis Report</span>
            </CardTitle>
          </CardHeader>
          <CardContent>
            <div className="prose max-w-none">
              <div className="bg-yellow-50 border border-yellow-200 rounded-lg p-4 mb-6">
                <p className="text-sm text-yellow-800 font-medium">
                  ⚠️ <strong>Disclaimer:</strong> This analysis is generated by AI and should not be considered as a replacement for professional medical advice. Please consult with a healthcare provider for proper medical diagnosis and treatment.
                </p>
              </div>
              
              <div className="whitespace-pre-wrap text-gray-800 leading-relaxed">
                {englishAnalysis}
              </div>
            </div>
          </CardContent>
        </Card>
      )}

      {/* Audio Analysis */}
      {audioUrl && (
        <Card>
          <CardHeader>
            <CardTitle className="flex items-center space-x-2">
              <Volume2 className="w-5 h-5 text-green-600" />
              <span>Audio Explanation (Urdu)</span>
            </CardTitle>
          </CardHeader>
          <CardContent>
            <div className="flex items-center space-x-4">
              <Button
                onClick={handlePlayAudio}
                variant="outline"
                className="flex items-center space-x-2"
                disabled={isPlaying}
              >
                {isPlaying ? (
                  <>
                    <VolumeX className="w-4 h-4" />
                    <span>Playing...</span>
                  </>
                ) : (
                  <>
                    <Volume2 className="w-4 h-4" />
                    <span>Play Audio</span>
                  </>
                )}
              </Button>
              
              <Button
                onClick={handleDownloadAudio}
                variant="ghost"
                size="sm"
                className="flex items-center space-x-2"
              >
                <Download className="w-4 h-4" />
                <span>Download</span>
              </Button>
            </div>
            
            <div className="mt-4 p-4 bg-green-50 rounded-lg">
              <p className="text-sm text-green-800">
                🎧 Listen to a personalized explanation of your medical report in Urdu, 
                delivered in a caring and easy-to-understand manner.
              </p>
            </div>
          </CardContent>
        </Card>
      )}
    </div>
  )
}